name: update_blogposts
on: 
    schedule:
        - cron: '0 */6 * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: self-hosted
        permissions:
            contents: write
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "50"
                feed_list: "https://dev.to/feed/ibshafique, https://medium.com/feed/@ibshafique"
